stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: maven:3-openjdk-11
          shellScript: mvn package -DskipTests
  - name: Build Docker with DIND
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: docker.dev.folio.org/mod-inventory-pronto:spitfire-latest
          pushRemote: true
          registry: docker.dev.folio.org
  - name: Deploy
    steps:
      - applyAppConfig:
          catalogTemplate: p-9tp2k:spitfire-helmcharts-mod-inventory-pronto
          version: 0.1.18
          answers:
            image.repository: docker.dev.folio.org/mod-inventory-pronto
            image.tag: spitfire-latest
          targetNamespace: spitfire
          name: mod-inventory-pronto
timeout: 60
notification: {}
