spring:
  application:
    name: mod-inventory-pronto
  datasource:
    # to boot up application despite of any DB connection issues
    continue-on-error: true
    password: ${DB_PASSWORD:pass}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:db}
    username: ${DB_USERNAME:user}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true
  liquibase:
    changeLog: classpath:db/changelog/changelog-master.xml
    enabled: true
  jackson:
    default-property-inclusion: NON_EMPTY
folio:
  tenant:
    validation:
      enabled: true
  logging:
    request:
      enabled: true
      level: basic
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,httptrace,liquibase
      base-path: /admin
#  endpoint:
#    health:
#      show-details: always
#      show-components: always
###################################################
# Disable all checks except for readiness
###################################################
  health:
    defaults:
      enabled: false
    readinessstate:
      enabled: true
server:
  port: 8081
