openapi: 3.0.0
info:
  title: Inventory API
  description: FOLIO Inventory API
  version: v1
servers:
  - url: http://localhost/
paths:
  /circluationItems/:
    get:
      description: Get items
      operationId: getCirculationItems
      parameters:
        - name: barcode
          description: Item barcode
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Items list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/circulationItems"
        "500":
          $ref: "#/components/responses/trait_validate_500"
  /circluationItems/{id}:
    get:
      description: Get circulation item by id
      operationId: getCirculationItemById
      parameters:
        - name: id
          description: Item identifier
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Items list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/circulationItem"
        "404":
          $ref: "#/components/responses/trait_validate_404"
        "500":
          $ref: "#/components/responses/trait_validate_500"
components:
  schemas:
    circulationItem:
      $ref: schemas/inventory/circulationItem.json
    circulationItems:
      $ref: schemas/inventory/circulationItems.json
    error:
      $ref: schemas/common/error.json
  responses:
    trait_validate_404:
      description: Not found error
      content:
        application/json:
          example: examples/error.sample
          schema:
            $ref: "#/components/schemas/error"
    trait_validate_500:
      description: Internal server error
      content:
        text/plain:
          schema:
            $ref: "#/components/schemas/error"
