openapi: 3.0.0
info:
  title: Inventory API
  description: FOLIO Inventory API
  version: v1
servers:
  - url: http://localhost/
paths:
  /circulation-items/{itemBarcode}:
    get:
      description: Get circulation item by barcode
      operationId: getCirculationItemByBarcode
      parameters:
        - name: itemBarcode
          description: Item barcode
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Items list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/circulationItem"
        "404":
          $ref: "#/components/responses/trait_validate_404"
        '422':
          $ref: "#/components/responses/trait_validate_422"
        '500':
          $ref: "#/components/responses/trait_validate_500"
components:
  schemas:
    circulationItem:
      $ref: schemas/inventory/circulationItem.json
    circulationItems:
      $ref: schemas/inventory/circulationItems.json
    error:
      $ref: schemas/core/error.json
    errors:
      $ref: schemas/core/errors.json
  responses:
    trait_validate_404:
      description: Not found error
      content:
        application/json:
          example: examples/error.sample
          schema:
            $ref: "#/components/schemas/error"
    trait_validate_422:
      description: Validation errors
      content:
        application/json:
          example: examples/errors.sample
          schema:
            $ref: "#/components/schemas/errors"
    trait_validate_500:
      description: Internal server error
      content:
        text/plain:
          schema:
            type: string
            example: Internal server error
